### ISSUE TITLE
Getting the Ouptut

### ISSUE THREAD

**Issue by JaMa-95** [fbarresi/BeckhoffJsonReadWriter#2]
Hello Frederico,
could you please help me with using your library.

I am using the following json:
```
{
  "name":"John",
  "age":30, 
  "car":"blue"
}
````
My MAIN looks like this: 
```
VAR
	parser : JsonParser;
	Json_Content : STRING(255);
	a : STRING;
        json : json_st;
END_VAR
parser(
	Execute:=FALSE , 
	File:= 'C:/temp/json_test.json', 
	ParseMethod:= 'Read' , // or even 'Write'
	Content:= 'json',
	HasError=> , 
	ErrorId=> );
a := json.name;
```
And lastly this is my struct:
```
TYPE json_st :
STRUCT
	name : STRING;
	age : INT;
	car : STRING;
END_STRUCT
END_TYP
```

The Code is getting executed so far, but the Struct Variables do not get updated with the Json Variables.
I tried lots of different things but do not see my problem. Could you please help me?

Thanks a lot

**Comment by fbarresi** [comment]
Closed due to inactivity.

**Comment by adisita** [comment]
Hi Frederico, 
 Was trying to use the library ( locally on my laptop)  ( both read and write) but I can't get it to work :( .  The code runs but doesn't read/write to/from a JSON file. and I'm not getting any errors  either. is there anything that  I miss ? I appreciate any help
