### ISSUE TITLE
No Read/Write 

### ISSUE THREAD

**Issue by adisita** [fbarresi/BeckhoffJsonReadWriter#3]
Hi Frederico,
Was trying to use the library ( locally on my laptop) ( both read and write) but I can't get it to work :( . The code runs but doesn't read/write to/from a JSON file. and I'm not getting any errors either. is there anything that I miss ? I appreciate any help

![image](https://user-images.githubusercontent.com/98291536/150705566-d1c827af-6254-4922-85e9-deb4488769be.png)

![image](https://user-images.githubusercontent.com/98291536/150705359-9b12fb5b-8a92-4185-9c85-b1d5dd4be334.png)

**Comment by fbarresi** [comment]
Hi!

I will look at this and report to you.

Best regards,

FB

**Comment by fbarresi** [comment]
I think in your case you just need a fully qualified variable name in the parameter content. In your case: `MAIN.stJSON_write` and `MAIN.stJSON_read`.
Can you please give a try?

I know the parameter "ParserMethod" allows misunderstandings, but you used it well 👍 
I will probably invert them in the next release even if would be a braking change.

Best regards,

FB

**Comment by fbarresi** [comment]
Did this change made the trick?

I just released a new version the should fix this misunderstanding with `read` or `write`. They now became `ReadFile` and `WriteFile`.

The software of the function will still work with older PLC implementations. 

Best regards, 

FB

**Comment by adisita** [comment]
hi, thanks for the clarifications. got it to work.  also would this work for an array of structures :) ? Thanks

**Comment by fbarresi** [comment]
Sorry, I missed out you question.
Yes it should.
