### ISSUE TITLE
CX9020

### ISSUE THREAD

**Issue by Fabi00815** [fbarresi/BeckhoffJsonReadWriter#6]
Hello,

is it possible to use this library on a CX9020 with Windows Embedded?

I Installed your lib but i get the error code 1862.

In your function you start a .exe in the background,right?

Is it possible to start .exe with Windows Embedded like on a CX9020?

**Comment by fbarresi** [comment]
Hi!

This error seems to come from the operating system.
(s. the  [error codes](https://infosys.beckhoff.com/english.php?content=../content/1033/tf6701_tc3_iot_communication_mqtt/374277003.html&id=))

It might be your are missing the .net framework. I don't know if the version 462 is available for your plc, but this is what you need.

For a better error description you might try to execute the twincat function manually and see the console log.

BR,
FB
